<?php 




function avvikk_custom_commerce_line_item_summary_link_info_alter(&$links) {
  // Link checkout button to the cart.
  if (isset($links['view_cart'])) {
    $links['view_cart']['title'] = 'Cart';
  }
}


/**
* Implements hook_form_FORMID_alter() to change the Add to Cart button to an image.
*/
function avvikk_custom_form_commerce_cart_add_to_cart_form_alter(&$form, &$form_state) {
  $form['submit']['#attributes']['title'] = $form['submit']['#attributes']['value'] = "Add to Cart";
  $form["attributes"]["field_size"]["#title"] = "Select Size";
  $line_item = $form_state['line_item'];
  // $product = commerce_product_load($line_item->commerce_product[LANGUAGE_NONE][0]['product_id']);
  $type = $line_item->data["context"]["entity"]["entity_type"];
  if($type == "node"){
  	$nid = $line_item->data["context"]["entity"]["entity_id"];
  	$node = node_load($nid);
	global $sold_out_items;
	$sold_out_items = array();
	foreach ($node->field_product_reference["und"] as $key => $value) {
	  $product = commerce_product_load($value["product_id"]);
	  if(!intval($product->commerce_stock["und"][0]["value"])){
	    //$sold_out_items[] =  intval($value["product_id"]);
	    $sold_out_items[] =  intval($product->field_size["und"][0]["value"]);
	  }
	}  	
  }
}

function avvikk_custom_commerce_checkout_page_info_alter(&$pages) {
  //dpm(array("PAGES" => $pages));
  if(!empty($pages['review'])) {
    $pages['review']['submit_value'] = t('Order now');
  }
}


function avvikk_custom_init(){
  if( strpos($_SERVER['REQUEST_URI'], 'product/men') ){
    menu_tree_set_path( 'main-menu', "shop/men" ); 
  } else if(  strpos($_SERVER['REQUEST_URI'], 'product/women') ){
    menu_tree_set_path( 'main-menu', "shop/women" ); 
  }
}

function avvikk_custom_form_alter(&$form, &$form_state, $form_id) {
  switch($form["#id"]){
    case "commerce-checkout-form-review":
      $options = array('absolute' => TRUE);
      $nid = 15; // Node ID
      $t_c_url = url('node/' . $nid, $options);
      $nid = 43; // Node ID
      $pri_url = url('node/' . $nid, $options);
/*      var_dump($form["commerce_payment"]["#prefix"]);
      exit;*/
      $form["commerce_payment"]["#suffix"] = "<div class='paypal_only'><h2>Paypal</h2><div>(As for now, paypal is the only payment option)</div></div>";
      $form['extra_pane__node__15']["#title"] = "I have read and accept the <a target='_blank' href='".$t_c_url."'>terms and conditions</a> and the <a target='_blank' href='".$pri_url."'>privacy policy</a>";
    break;
  }

  if (isset($form['type']) && $form['type']['#value'] . '_node_settings' == $form_id) {
    $form['workflow']['upload_' . $form['type']['#value']] = array(
      '#type' => 'radios',
      '#title' => t('Attachments'),
      '#default_value' => variable_get('upload_' . $form['type']['#value'], 1),
      '#options' => array(t('Disabled'), t('Enabled')),
    );
  }
}

?>