<?php 




function avvikk_custom_commerce_line_item_summary_link_info_alter(&$links) {
  // Link checkout button to the cart.
  if (isset($links['view_cart'])) {
    $links['view_cart']['title'] = 'Cart';
  }
}


/**
* Implements hook_form_FORMID_alter() to change the Add to Cart button to an image.
*/
function avvikk_custom_form_commerce_cart_add_to_cart_form_alter(&$form, &$form_state) {
  $line_item = $form_state['line_item'];
  // $product = commerce_product_load($line_item->commerce_product[LANGUAGE_NONE][0]['product_id']);
  $type = $line_item->data["context"]["entity"]["entity_type"];
  if($type == "node"){
  	$nid = $line_item->data["context"]["entity"]["entity_id"];
  	$node = node_load($nid);
	global $sold_out_items;
	$sold_out_items = array();
	foreach ($node->field_product_reference["und"] as $key => $value) {
	  $product = commerce_product_load($value["product_id"]);
	  if(!intval($product->commerce_stock["und"][0]["value"])){
	    //$sold_out_items[] =  intval($value["product_id"]);
	    $sold_out_items[] =  intval($product->field_size["und"][0]["value"]);
	  }
	}  	
  }
}



?>